name: Test ROS CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2      
    - name: Install ROS
      uses: ros-tooling/setup-ros@v0.1
      with:
        required-ros-distributions: kinetic
