name: Test ROS CI

on: [push, pull_request]

env:
  ROS_CI_DESKTOP: "`lsb_release -cs`"  # gives Ubuntu name, e.g. [precise|trusty|...]
  ROS_PARALLEL_JOBS: "-j8 -l6"

jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2      
    - name: Install ROS
      uses: ros-tooling/setup-ros@0.1.1
      with:
        required-ros-distributions: kinetic
